version: '3'
services:
  postgres:
    container_name: postgres_general
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  redis:
    container_name: redis_general
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data