version: '3'
services:
  postgres:
    container_name: postgres_nestjscrud
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5434:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  redis:
    container_name: redis_nestjscrud
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data